### ISSUE TITLE
unitTest is failing

### ISSUE THREAD

**Issue by robsonpeixoto** [batect/batect-sample-golang#86]
```
❯ ./batect unitTest
Running unitTest...
golang-build-env: pulling golang:1.16.4: downloading: 52.7 MB of 197.8 golang-build-env: pulling golang:1.16.4: downloading: 53.2 MB of 197.8 golang-build-env: running ginkgo -tags unitTests


Error: Could not run container golang-build-env.
Starting container '2efc1489e06d07ba3dd06e370e8d8c97bd9a162acbf7991262166df5bf6d806e' failed: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "ginkgo": executable file not found in $PATH: unknown

Clean up: done

The task unitTest failed. See above for details.
```

**Comment by charleskorn** [comment]
Hi @robsonpeixoto, I might need to make this clearer in the readme (or even add something to the app to show a better error message), but you need to run `./batect setup` before running any other tasks. `setup` downloads some dependencies that can't easily be embedded in the Docker image used for the build environment.

**Comment by robsonpeixoto** [comment]
But why isn't it defining `setup` as `prerequisites`?

**Comment by charleskorn** [comment]
It's a good question - because `setup` can take some time, and only has to be run once, I thought it would be a better experience to not have `setup` run automatically every time.

In an ideal world, we'd be able to bake `ginkgo` into the base image and then the `setup` task wouldn't be necessary, or just pull it down when it's needed. Perhaps the testing steps could check that `ginkgo` has been installed before running it?

**Comment by robsonpeixoto** [comment]
This solution is very interesting: https://taskfile.dev/#/usage?id=prevent-unnecessary-work
